// <auto-generated />
namespace ShopBanDoDienTu_Nhom1.IdentityMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddResetPasswordTokenAndFindByResetPasswordToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddResetPasswordTokenAndFindByResetPasswordToken));
        
        string IMigrationMetadata.Id
        {
            get { return "202404081047352_AddResetPasswordTokenAndFindByResetPasswordToken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
